apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devguard-staging

resources:
  - ../../base

patchesStrategicMerge:
  - ingress-host.yaml

configMapGenerator:
  - name: devguard-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO

replicas:
  - name: devguard-api
    count: 2
  - name: devguard-cpp-engine
    count: 2
  - name: devguard-frontend
    count: 2
